refactor: use async block and multihashing interface
ipfs/js-ipfs-merkle-dag pull request #51
Opened 2016-09-28 09:14 UTC by dignifiedquire

2016-10-03 14:11 UTC, haadcode reviewed
LGTM! This is a much needed fix, let's get it into the release asap!

2016-10-03 14:13 UTC, haadcode commented
Erm. The new PR view is confusing. The comment ^ was meant for the fix for `merkeledag.proto` and fs.readFileSync.

2016-10-03 15:38 UTC, diasdavid commented on src/dag-node.js
> +    return `DAGNode <data: "${this.data.toString()}", links: ${this.links.length}>`
Why change the `toString` this is a breaking change

2016-10-03 15:54 UTC, daviddias requested changes

2016-10-03 15:54 UTC, diasdavid commented on src/dag-node.js
> +    return `DAGNode <data: "${this.data.toString()}", links: ${this.links.length}>`
Why change the toString this is a breaking change

2016-10-03 15:55 UTC, dignifiedquire commented on src/dag-node.js
> +    return `DAGNode <data: "${this.data.toString()}", links: ${this.links.length}>`
The alternative is to make `toString` async (to be able to fetch `size` and `hash`), which I found much worse than dropping them from the output

2016-10-26 11:46 UTC, dignifiedquire commented
Closing as this module is deprecated now. Ref #62

2016-10-26 11:46 UTC, closed without merging